# Generated by Django 3.1.7 on 2021-04-18 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20210418_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ein', models.CharField(max_length=10)),
                ('deductibility', models.BooleanField()),
                ('url', models.URLField()),
                ('cause', models.TextField(max_length=100)),
                ('catagory', models.IntegerField(choices=[('PERSON', 1), ('HEALTH', 2), ('ANIMALS', 3), ('ENVIRONMENT', 4), ('EDUCATION', 5)])),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.contact')),
            ],
        ),
    ]
