# Generated by Django 3.1.7 on 2021-04-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210418_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='charityuser',
            name='membertype',
            field=models.IntegerField(choices=[(1, 'VOLUNTERR'), (2, 'CHARITY')], default=0),
            preserve_default=False,
        ),
    ]
