# Generated by Django 3.1.7 on 2021-04-19 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210419_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferredCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.IntegerField(choices=[(1, 'PERSON'), (2, 'HEALTH'), (3, 'ANIMALS'), (4, 'ENVIRONMENT'), (5, 'EDUCATION')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
