# Generated by Django 3.1.7 on 2021-04-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_preferredcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='charityuser',
            name='distance',
            field=models.IntegerField(null=True),
        ),
    ]
