# Generated by Django 3.1.7 on 2021-04-19 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_charityuser_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferredAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[(1, 'COOK'), (2, 'CLEAN'), (3, 'TEACH'), (4, 'PARTY')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
